export const seznam = [
  {
    name: 'k moři',
    cestovniDoklady: [
      'OP',
      'Cestovní pas',
      'Kartička zdravotního pojištění',
      'Cestovní pojištění',
      'Řidičák (zelená karta)',
      'Platební karty',
      'Voucher',
      'Letenka',
      'Vízum',
      'Lékařské potvrzení',
    ],
    obleceni: [
      'Plavky',
      'Spodní prádlo',
      'Ponožky',
      'Obuv (i do vody)',
      'Kraťasy',
      'Tričko',
      'Tílko',
      'Klobouk/Kšiltovka',
      'Šaty?',
      'Pyžamo',
    ],
    hygiena: [
      'Zubní kartáček',
      'Pasta',
      'Hřeben',
      'Sprchový gel',
      'šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holicí potřeby',
    ],
    elektronika: ['Mobilní telefon', 'Nabíječka', 'Powerbanka', 'Sluchátka'],
    ostatni: [
      'Léky',
      'Sluneční brýle',
      'Potápěčské vybavení',
      'Opalovací krém',
      'Slunečník',
      'Deky/karimatky',
      'Nafukovací lehátko',
    ],
  },
  {
    name: 'na čundr',
    cestovniDoklady: [
      'Občanský průkaz',
      'Cestovní pas',
      'Kartička zdravotního pojištění',
      'Cestovní pojištění',
      'Řidičák (zelená karta)',
      'Platební karty',
      'Lékařské potvrzení',
    ],
    obleceni: [
      'Pohodlná obuv',
      'Spodní prádlo',
      'Ponožky',
      'Tričko',
      'Kraťasy',
      'Kalhoty',
      'Mikina',
      'Bunda',
      'Klobouk/čepice',
    ],
    hygiena: [
      'Zubní kartáček',
      'Pasta',
      'Hřeben',
      'Sprchový gel',
      'šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holící potřeby',
      'Toaletní papír',
    ],
    elektronika: ['Mobilní telefon', 'Nabíječka', 'Powerbanka', 'Sluchátka'],
    ostatni: [
      'Léky',
      'Sluneční brýle',
      'Opalovací krém',
      'Stan',
      'Spacák',
      'Deka',
      'Zapalovač/sirky',
      'Pláštěnka',
      'Nůž',
      'Baterka',
      'Mapa',
      'Láhev na vodu',
      'Nádobí',
    ],
  },
  {
    name: 'na služební cestu',
    cestovniDoklady: [
      'OP',
      'pas',
      'vízum',
      'kartička pojišťovny',
      'cestovní pojištění',
      'řidičák',
      'letenka',
    ],
    obleceni: [
      'sako',
      'pracovní kalhoty',
      'košile',
      'svetr',
      'ponožky',
      'spodní prádlo',
      'opasek',
      'šaty',
      'kalhoty',
      'oblečení do hotelu',
      'pyžamo',
      'pracovní obuv',
      'boty do hotelu',
      'boty do města',
    ],
    hygiena: [
      'pcr test',
      'antigenní test',
      'rouška',
      'respirátor',
      'zubní kartáček',
      'zubní nit',
      'pasta na zuby',
      'hřeben',
      'deodorant',
      'parfém',
      'sprchový gel',
      'šampon',
    ],
    elektronika: [
      'mobilní telefon',
      'pracovní telefon',
      'nabíječka na telefon',
      'notebook',
      'myš',
    ],
    ostatni: ['pracovní ID karta', 'informace o ubytování - pin do hotelu'],
  },
  {
    name: 'na hory',
    cestovniDoklady: [
      'OP',
      'pas',
      'vízum',
      'kartička pojišťovny',
      'cestovní pojištění',
      'řidičák',
    ],
    obleceni: [
      'ponožky',
      'zateplené ponožky',
      'spodní prádlo',
      'termo prádlo',
      'tričko',
      'svetr',
      'kalhoty',
      'pyžamo',
      'bunda',
      'kalhoty na sportování',
      'bunda na sportování',
      'brýle',
      'čepice',
      'rukavice',
      'šála',
    ],
    hygiena: [
      'zubní kartáček',
      'zubní pasta',
      'hřeben',
      'deodorant',
      'sprchový gel',
      'šampon',
    ],
    elektronika: ['mobilní telefon', 'nabíječka'],
    ostatni: [
      'první pomoc',
      'lyže',
      'hůlky na lyžování',
      'snowboard',
      'opalovací krém',
    ],
  },
];
