export const seznam = [
  {
    name: 'moře',
    cestovniDoklady: [
      'Občanský průkaz',
      'Cestovní pas',
      'Kartička zdravotní pojišťovny',
      'Cestovní pojištění',
      'Řidičský průkaz (zelená karta)',
      'Platební karty',
      'Voucher',
      'Letenka',
      'Vízum',
      'Lékařská potvrzení',
    ],
    obleceni: [
      'Spodní prádlo',
      'Ponožky',
      'Pyžamo',
      'Plavky',
      'Tričko',
      'Tílko',
      'Kraťasy',
      'Šaty',
      'Klobouk/kšiltovka',
      'Obuv',
      'Obuv do vody',
    ],
    hygiena: [
      'Zubní kartáček',
      'Zubní pasta',
      'Zubní nit/mezizubní kartáček',
      'Hřeben',
      'Sprchový gel',
      'Šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holicí potřeby',
      'PCR test',
      'Antigenní test',
      'Rouška',
      'Respirátor',
    ],
    elektronika: ['Mobilní telefon', 'Nabíječka', 'Powerbanka', 'Sluchátka'],
    ostatni: [
      'Léky',
      'Sluneční brýle',
      'Potápěčské vybavení',
      'Opalovací krém',
      'Slunečník',
      'Deky/karimatky',
      'Nafukovací lehátko',
      'Kniha',
    ],
  },
  {
    name: 'čundr',
    cestovniDoklady: [
      'Občanský průkaz',
      'Cestovní pas',
      'Kartička zdravotní pojišťovny',
      'Cestovní pojištění',
      'Řidičský průkaz (zelená karta)',
      'Platební karty',
      'Lékařské potvrzení',
    ],
    obleceni: [
      'Spodní prádlo',
      'Ponožky',
      'Tričko',
      'Kraťasy',
      'Kalhoty',
      'Mikina',
      'Bunda',
      'Klobouk/čepice',
      'Pohodlná obuv',
    ],
    hygiena: [
      'Zubní kartáček',
      'Zubní pasta',
      'Zubní nit/mezizubní kartáček',
      'Hřeben',
      'Sprchový gel',
      'Šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holicí potřeby',
      'Toaletní papír',
      'PCR test',
      'Antigenní test',
      'Rouška',
      'Respirátor',
    ],
    elektronika: ['Mobilní telefon', 'Nabíječka', 'Powerbanka', 'Sluchátka'],
    ostatni: [
      'Léky',
      'Sluneční brýle',
      'Opalovací krém',
      'Stan',
      'Spacák',
      'Deka',
      'Zapalovač/sirky',
      'Pláštěnka',
      'Nůž',
      'Baterka',
      'Mapa',
      'Láhev na vodu',
      'Nádobí',
      'Kytara',
    ],
  },
  {
    name: 'služební cesta',
    cestovniDoklady: [
      'Občanský průkaz',
      'Cestovní pas',
      'Kartička zdravotní pojišťovny',
      'Cestovní pojištění',
      'Řidičský průkaz (zelená karta)',
      'Platební karty',
      'Letenka',
      'Vízum',
    ],
    obleceni: [
      'Spodní prádlo',
      'Ponožky',
      'Pyžamo',
      'Košile',
      'Sako',
      'Svetr',
      'Šaty',
      'Kalhoty',
      'Pracovní kalhoty',
      'Opasek',
      'Oblečení do hotelu',
      'Pracovní obuv',
      'Volnočasová obuv',
    ],
    hygiena: [
      'Zubní kartáček',
      'Zubní pasta',
      'Zubní nit/mezizubní kartáček',
      'Hřeben',
      'Sprchový gel',
      'Šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holicí potřeby',
      'Parfém',
      'PCR test',
      'Antigenní test',
      'Rouška',
      'Respirátor',
    ],
    elektronika: [
      'Mobilní telefon',
      'Pracovní telefon',
      'Nabíječka',
      'Powerbanka',
      'Notebook',
      'Sluchátka',
      'Myš',
    ],
    ostatni: [
      'Léky',
      'Pracovní ID karta',
      'Informace o ubytování - pin do hotelu',
      'Deštník',
    ],
  },
  {
    name: 'hory',
    cestovniDoklady: [
      'Občasnký průkaz',
      'Cestovní pas',
      'Kartička zdravotní pojišťovny',
      'Cestovní pojištění',
      'Řidičský průkaz (zelená karta)',
      'Platební karty',
      'Voucher',
      'Letenka',
      'Vízum',
    ],
    obleceni: [
      'Spodní prádlo',
      'Ponožky',
      'Zateplené ponožky',
      'Pyžamo',
      'Tričko',
      'Svetr',
      'Termo prádlo',
      'Kalhoty',
      'Kalhoty na sportování',
      'Bunda',
      'Bunda na sportování',
      'Brýle',
      'Čepice',
      'Rukavice',
      'Šála',
    ],
    hygiena: [
      'Zubní kartáček',
      'Zubní pasta',
      'Hřeben',
      'Sprchový gel',
      'Šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holicí potřeby',
      'PCR test',
      'Antigenní test',
      'Rouška',
      'Respirátor',
    ],
    elektronika: ['Mobilní telefon', 'Nabíječka', 'Sluchátka'],
    ostatni: [
      'Léky',
      'První pomoc',
      'Lyže',
      'Hůlky na lyžování',
      'Snowboard',
      'Opalovací krém',
    ],
  },
];
