export const seznam = [
  {
    name: 'K moři',
    cestovniDoklady: [
      'OP',
      'Cestovní pas',
      'Kartička zdravotního pojištění',
      'Cestovní pojištění',
      'Řidičák (zelená karta)',
      'Platební karty',
      'Voucher',
      'Letenka',
      'Vízum',
      'Lékařské potvrzení',
    ],
    obleceni: [
      'Plavky',
      'Spodní prádlo',
      'Ponožky',
      'Obuv (i do vody)',
      'Kraťasy',
      'Tričko',
      'Tílko',
      'Klobouk/Kšiltovka',
      'Šaty?',
      'Pyžamo',
    ],
    hygiena: [
      'Zubní kartáček',
      'Pasta',
      'Hřeben',
      'Sprchový gel',
      'šampon',
      'Deodorant',
      'Papírové kapesníky',
      'Holicí potřeby',
    ],
    elektronika: ['Mobilní telefon', 'Nabíječka', 'Powerbanka', 'Sluchátka'],
    ostatni: [
      'Léky',
      'Sluneční brýle',
      'Potápěčské vybavení',
      'Opalovací krém',
      'Slunečník',
      'Deky/karimatky',
      'Nafukovací lehátko',
    ],
  },
  {
    name: 'Čundr',
    cestovniDoklady: [],
    obleceni: [],
    hygiena: [],
    ostatni: [],
  },
  {
    name: 'Čundr',
    cestovniDoklady: [],
    obleceni: [],
    hygiena: [],
    ostatni: [],
  },
  {
    name: 'Čundr',
    cestovniDoklady: [],
    obleceni: [],
    hygiena: [],
    ostatni: [],
  },
];
